export const ACCESSORY_LIST_REQUEST = 'ACCESSORY_LIST_REQUEST'
export const ACCESSORY_LIST_SUCCESS = 'ACCESSORY_LIST_SUCCESS'
export const ACCESSORY_LIST_FAIL = 'ACCESSORY_LIST_FAIL'

export const ACCESSORY_DETAILS_REQUEST = 'ACCESSORY_DETAILS_REQUEST'
export const ACCESSORY_DETAILS_SUCCESS = 'ACCESSORY_DETAILS_SUCCESS'
export const ACCESSORY_DETAILS_FAIL = 'ACCESSORY_DETAILS_FAIL'

export const ACCESSORY_DELETE_REQUEST = 'ACCESSORY_DELETE_REQUEST'
export const ACCESSORY_DELETE_SUCCESS = 'ACCESSORY_DELETE_SUCCESS'
export const ACCESSORY_DELETE_FAIL = 'ACCESSORY_DELETE_FAIL'

export const ACCESSORY_CREATE_REQUEST = 'ACCESSORY_CREATE_REQUEST'
export const ACCESSORY_CREATE_SUCCESS = 'ACCESSORY_CREATE_SUCCESS'
export const ACCESSORY_CREATE_FAIL = 'ACCESSORY_CREATE_FAIL'
export const ACCESSORY_CREATE_RESET = 'ACCESSORY_CREATE_RESET'

export const ACCESSORY_UPDATE_REQUEST = 'ACCESSORY_UPDATE_REQUEST'
export const ACCESSORY_UPDATE_SUCCESS = 'ACCESSORY_UPDATE_SUCCESS'
export const ACCESSORY_UPDATE_FAIL = 'ACCESSORY_UPDATE_FAIL'
export const ACCESSORY_UPDATE_RESET = 'ACCESSORY_UPDATE_RESET'